// APRENDENDO SOBRE A BIBLIOTECA MATH

const mat = document.querySelector("#mat");

const num = Math.random()*10; // FAZ MULTIPLICADO POR DEZ PRA APARACER UM NÚMERO ALEATÓRIO ENTRE 0 E 9

// mat.innerHTML = Math.round(num);
mat.innerHTML = Math.pow(10,3); // POTENCIA PRIMEIRO A BASE E DEPOIS O EXPOENTE NESSE EXEMPLO 10 ELEVADO A 2

//Math.floor(num)+1; UM DOS MÉTODOS PARA FAZER NÚMEROS ALEATÓRIOS ENTRE 1 E 10

//FLOOR --> PEGAR O NÚMERO INTEIRO
// ROUND --> MESMA COISA QUE O FLOOR MAS ESSE CHEGA ATÉ O ÚLTIMO NUMERO ESTIPULADO NESSE CASO 10
// RANDOM --> GERAR NÚMERO ALEATÓRIO